language: haskell
ghc:
  - "7.8"
  - "7.10"
notifications:
email: true

before_install:
  - git clone https://github.com/ComputationWithBoundedResources/term-rewriting-applicative.git
  - cd term-rewriting-applicative && cabal install