flags:
  transformers-compat:
    five-three: true
packages:
- .
- ../term-rewriting-xml
- ../term-rewriting-applicative
extra-deps:
- List-0.6.2
- QuickCheck-2.11.3
- ansi-terminal-0.8.0.4
- ansi-wl-pprint-0.6.8.2
- base-compat-0.10.4
- cmdargs-0.10.20
- colour-2.3.4
- dlist-0.8.0.4
- exceptions-0.10.0
- fgl-5.6.0.0
- graphviz-2999.20.0.2
- hexpat-0.20.13
- multiset-0.3.4
- polyparse-1.12
- primitive-0.6.4.0
- random-1.1
- temporary-1.3
- term-rewriting-0.2.1.1
- tf-random-0.5
- transformers-compat-0.6.2
- union-find-array-0.1.0.2
- utf8-string-1.0.1.1
- wl-pprint-text-1.2.0.0
- ghc-paths-0.1.0.9
- network-2.7.0.2
- syb-0.7
resolver: ghc-8.4
